server:
  host: 0.0.0.0
  port: 8000
cache:
  # username: ""
  # password: ""
database:
  # host: "localhost"
  # port: 5432
  # user: "sgbf"
  # password: ""
  # database: "sgbf"
onesignal:
  # key: ""
  id: ""
tracing:
  error_reporting:
    # sentry_dsn: ""
    sampling_rate: 0.1
  logger:
      level: "info"