{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sgbf.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "sgbf.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sgbf.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
